### ISSUE TITLE
How to get incident timeline

### ISSUE THREAD

**Issue by tatdatpham** [demisto/demisto-py#39]
I try to get all incident timeline. How to do that. I can't find any api to do that
Thank 
![image](https://user-images.githubusercontent.com/3429970/83712869-ebb00f80-a650-11ea-99dd-4c82669407ef.png)

**Comment by glicht** [comment]
@amshamah419 can you check if this is supported

**Comment by amshamah419** [comment]
Just to update, I'm looking into this. It appears we don't have a dedicated endpoint for incident timelines, however, there may be a workaround solution available to us. I'm trying to confirm that it works as intended.

**Comment by tatdatpham** [comment]
Thank, my idea is sync all comment or any action in warroom to another system. We try to write another portal, warpper on top of Demisto.

**Comment by amshamah419** [comment]
So I did manage to dig further into this and from what I see, I don’t believe it is possible at this time. The incident timeline objects are war room entries and indistinguishable via the API. It may be possible to retrieve the entries and filter through them locally, but this would be outside of the demisto-py package.

**Comment by tatdatpham** [comment]
So have anyway to get them? Connect DB?
As i mention above, i try to build new portal (warpper thanos). So engineer team update information into thanos and customer can see information in my portal

**Comment by amshamah419** [comment]
@tatdatpham You can retrieve war room entries and make the request with a filter object. Then the entries you wish not to present to the customer, you could filter out locally. 

You shouldn't need DB access to facilitate this. The issue here is that on the Demisto server, there is no _dedicated_ endpoint which would deliver **only** the incident timeline objects. You can, however, retrieve all of the incident war room entries and filter out any of the entries you don't need.

I would recommend reaching out to your CSM as they may have some experience or familiarity with a mirroring portal and could help guide you in implementing this.

**Comment by tatdatpham** [comment]
> @tatdatpham You can retrieve war room entries and make the request with a filter object. Then the entries you wish not to present to the customer, you could filter out locally.
> 
> You shouldn't need DB access to facilitate this. The issue here is that on the Demisto server, there is no _dedicated_ endpoint which would deliver **only** the incident timeline objects. You can, however, retrieve all of the incident war room entries and filter out any of the entries you don't need.
> 
> I would recommend reaching out to your CSM as they may have some experience or familiarity with a mirroring portal and could help guide you in implementing this.

Thank for your guide @amshamah419 !
Could you tell me how to retrieve war room entries? Can i do it by using demisto-py? If that is true, what api that i can do it.
