### ISSUE TITLE
Wrong return type for search_incidents

### ISSUE THREAD

**Issue by smadessis** [demisto/demisto-py#44]
According to the documentation, search_incidents is supposed to return an "InlineResponse200" composed of an array of Incidents and the total of incidents as an integer. 
https://github.com/demisto/demisto-py/blob/master/docs/DefaultApi.md#return-type-61

However it's currently returning a type "Incident", even if the content seems correct, which prevents the use of the attributes to get the data.
https://github.com/demisto/demisto-py/blob/3a23868cf047e762b1676c9ba468c1ff2c4726b9/demisto_client/demisto_api/api/default_api.py#L6097

In comparison, search_indicators which is similar function is correct and returns an object and not an Indicator:
https://github.com/demisto/demisto-py/blob/3a23868cf047e762b1676c9ba468c1ff2c4726b9/demisto_client/demisto_api/api/default_api.py#L5139

**Comment by glicht** [comment]
Thanks for reporting this. We will check this out.

**Comment by amshamah419** [comment]
I believe I found the reason for why it was set as `Incident`. It was due to an issue where `demisto-py` would not map the object correctly and instead would return `None` for the `incidents` object. We originally overrode this to prevent the request from returning an object with no incidents.

I came up with a better way to handle this and will have a fix out momentarily.
